### ISSUE TITLE
Content of timestamp.proto in dotnet part is wrong

### ISSUE THREAD

**Issue by MrAriasto** [DKE-Data/agrirouter-api-protobuf-definitions#52]
**Describe the bug**
The content of dotnet/google/protobuf/timestamp.proto is different to original file from google protobuf (https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto) 
The generate.sh throws errors. 

**Expected behavior**
Change file content to content of 
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto
will resolve the problem.

**Comment by agrirouter** [comment]
Moin Sascha, kannst Du es bitte prüfen. Danke Dir…

Mit freundlichen Grüßen / Best Regards / С уважением


[Logo Positive Transparent]

Dipl.-Kaufmann
Alexander Hammerschmidt

IT Management

DKE-Data GmbH & Co. KG
Albert-Einstein-Str. 42
49076 Osnabrück

Geschäftsführer: Dr.-Ing. Jens Möller

Phone:+49 541 20197 003
Mobil: +49 175 / 9378 380
Mail: a.hammerschmidt@dke-data.com<mailto:a.hammerschmidt@dke-data.com>
Web: my-agrirouter.com

------------------------------------------------------------------------------

Follow us on:

[twitter]<https://twitter.com/dke_data>  [facebook] <https://www.facebook.com/agrirouter>   [youtube] <https://www.youtube.com/channel/UCbkt9ThYm4AI45_sjSIO6gA>

--------------------------------------------------------------------------------

Von: Sebastian Richter <notifications@github.com>
Gesendet: Mittwoch, 12. Februar 2020 14:06
An: DKE-Data/agrirouter-api-protobuf-definitions <agrirouter-api-protobuf-definitions@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [DKE-Data/agrirouter-api-protobuf-definitions] Content of timestamp.proto in dotnet part is wrong (#52)


Describe the bug
The content of dotnet/google/protobuf/timestamp.proto is different to original file from google protobuf (https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto)
The generate.sh throws errors.

Expected behavior
Change file content to content of
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto
will resolve the problem.
